#  _____      _    _____                   _   _
# |  __ \    | |  / ____|                 | | | |
# | |__) | __| |_| |  __ _ __ _____      _| |_| |__
# |  ___/ '__| __| | |_ | '__/ _ \ \ /\ / / __| '_ \
# | |   | |  | |_| |__| | | | (_) \ V  V /| |_| | | |
# |_|   |_|   \__|\_____|_|  \___/ \_/\_/  \__|_| |_|
#                                          by Pretti_

#
# Permissions:
# - prtg.command        = To be able to access the list of commands with the /growth;
# - prtg.command.reload = To be able to reload the plugin with the /growth reload;

#
# PLANTS
#
plants:
  method: BLACKLIST
  values: [] # Remove '[]' and add materials plants
  #- "CARROT"
  #- "POTATO"